# Generated by Django 2.2.11 on 2020-04-03 10:23

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0074_create_light_admin_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='search_vector_en',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='search_vector_fi',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='search_vector_ru',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='search_vector_simple',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='search_vector_sv',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
    ]
